<html>
	<head>
		<title>Test</title>
	</head>
	<body>
		<table>
			<thead><tr><th>First</th><th>Second</th><th>Third</th></tr></thead>
			<tbody><tr><td>1</td><td>2</td><td>3</td></tr>
				<tr><td>4</td><td>5</td><td>6</td></tr>
				<tr><td>7</td><td>8</td><td>9</td></tr>
				<tr><td>10</td><td>11</td><td>12</td></tr>
				<tr><td>13</td><td>14</td><td>15</td></tr>
				<tr><td>16</td><td>17</td><td>18</td></tr>
				<tr><td>19</td><td>20</td><td>21</td></tr>
			</tbody>
		</table>
	</body>
	
</html>
